### ISSUE TITLE
No results returned

### ISSUE THREAD

**Issue by kitmonkman** [kinabalu/obsidian-oura-plugin#13]
Hi, I'm being dim. I've installed the plugin and pasted in Oura Personal Access Token, but on attempting to run 'Insert Oura Ring Stats', I get no results. Any advice as to what I'm doing wrong would be very welcome. Thanks.

 at new t (app.js:1:2015247)
    at sK (app.js:1:2015439)
    at app.js:1:2016118
    at app.js:1:237079
    at Object.next (app.js:1:237184)
    at a (app.js:1:235902)

t	@	app.js:1
sK	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
(anonymous)	@	app.js:1
a	@	app.js:1
Promise.then (async)		
step	@	plugin:obsidian-oura-plugin:30
eval	@	plugin:obsidian-oura-plugin:31
__awaiter	@	plugin:obsidian-oura-plugin:27
editorCallback	@	plugin:obsidian-oura-plugin:1190
e.mobileOnly.ql.isMobile.e.checkCallback	@	app.js:1
xK	@	app.js:1
t.onChooseItem	@	app.js:1
t.onChooseSuggestion	@	app.js:1
t.selectSuggestion	@	app.js:1
e.useSelectedItem	@	app.js:1
(anonymous)	@	app.js:1
e.handleKey	@	app.js:1
e.onKeyEvent	@	app.js:1

**Comment by kinabalu** [comment]
no way to test this but hoping that 0.2.0 fixes

**Comment by kitmonkman** [comment]
It does! Many, many thanks.
