### ISSUE TITLE
Missing metric: Resilience

### ISSUE THREAD

**Issue by pedramamini** [kinabalu/obsidian-oura-plugin#15]
Great work on the recent update! Is resilience an available metric to expose via the template?

**Comment by kinabalu** [comment]
Thanks glad it is working out for folks.

Re: resilience -- it's not a metric but an aggregate of metrics over a 14 day period (https://support.ouraring.com/hc/en-us/articles/25358829055251-Resilience) which they don't provide an actual algorithm for exactly how it's calculated unfortunately.

if there are specific pieces of data or if someone wants to work backwards to figure out exactly the algorithm we could integrate it here.
