### ISSUE TITLE
Allow adding to frontmatter of a note

### ISSUE THREAD

**Issue by kinabalu** [kinabalu/obsidian-oura-plugin#3]
Should we look into doing something like

```
- oura
  - sleep
    - score: 86
```

perhaps this means easier to pull with something like dataview?

**Comment by zachdaniel** [comment]
This would be awesome :D

**Comment by kinabalu** [comment]
New version will use the double colon so it can be used with things like dataview.

i.e. instead of `Bedtime Start:` it will be `Bedtime_Start::` so you can reference easier

**Comment by zachdaniel** [comment]
Hey there! Any idea when the new version using the new format might be released?

**Comment by kinabalu** [comment]
just updated and it uses the new names for items, and uses double colon so should be reference-able from dataview
