### ISSUE TITLE
Zip of release source files issue

### ISSUE THREAD

**Issue by ParzivalWins** [kinabalu/obsidian-oura-plugin#4]
The zip contains a main.ts vs. main.js.  Does load properly in Obsidian. However, individual files downloaded works.

**Comment by ParzivalWins** [comment]
Otherwise, working great. Thank you.

**Comment by kinabalu** [comment]
Yes, the zip should contain a main.ts, as this is written in TypeScript and uses a transpiler to convert to javascript. The zip is the source code, you should probably use Obsidian42 - BRAT to install this until it's been released in the community plugins section.

Thanks for using! Looking forward to hear more suggestions!
