### ISSUE TITLE
Can't find the oura ring command

### ISSUE THREAD

**Issue by zachdaniel** [kinabalu/obsidian-oura-plugin#6]
Hey there! I'm still poking around to figure out why I can't find it, but I've installed the plugin using BRAT and I haven't been able to actually run the command. My access token is functionally checking my email and displaying it in settings, so I'm not sure what's up :)

**Comment by zachdaniel** [comment]
interesting, it works on my laptop but not my ipad. No big deal.

**Comment by kinabalu** [comment]
@zachdaniel are you using different plugin directories between laptop and ipad? have to make sure to put the personal access token in to both if so

**Comment by zachdaniel** [comment]
I don't believe so, I'm just using obsidian sync so the directories should be the same.

**Comment by kinabalu** [comment]
new version coming soon should tell you if access token exists or not, and also if there was data for that day.

also considering adding a command to input the date in manually as well, etc
