### ISSUE TITLE
[Enhancement] Pull data such as HRV, breathing, temp using Oura's v2 API

### ISSUE THREAD

**Issue by zenminimalist** [kinabalu/obsidian-oura-plugin#7]
I was wondering if your plugin could be expanded to include things such as average HRV value or average breathing rate, temperature etc. 

Maybe that's related to the fact that the plugin is using v1 of the API, not sure. But v2 is availalbe. 

Also, it would be awesome if one could define a date range i.e. 2022-06-23 to 2022-07-08, and the plugin would pull in these values.

**Comment by marcofeltmann** [comment]
Feels like the first part equals #8 but the latter would be awesome. Although it feels a bit like #2 it's more the other way round: Not extract fields but inject URL params.

One could insert that configured query into a weekly/monthly/quaterly/yearly template for the Periodic Notes plugin.

**Comment by kinabalu** [comment]
hoping that the 0.2.0 has fixed this -- we need more folks to test however.
