### ISSUE TITLE
Add some parameters 

### ISSUE THREAD

**Issue by mcwvanvliet** [kinabalu/obsidian-oura-plugin#8]
It would be really nice to add some parameters to the oura-obsidian import. 
especially hrv could be interesting to log next to other journaling you can do in Obsidian. 

these parameters would be nice additions: 
hr_rest - readiness.score_resting_hr
breath_fq - sleep.breath_average
hrv_avg - readiness.score_hrv_balance
temperature - readiness.score_temperature

**Comment by kinabalu** [comment]
a lot of the new parameters exist in 0.2.0, hoping it works since I can't test since no ring
