### ISSUE TITLE
Plugin does non print data from the Oura Cloud

### ISSUE THREAD

**Issue by imatosyan** [kinabalu/obsidian-oura-plugin#9]
Steps to reproduce
- I have Daily Note opened with file name 2024-01-23
- cursor is ready for typing text
- I initiate Oura Ring: Insert Oura Ring Stats command

Bad behaviour
- nothing happens

Expected behaviour
- Oura Ring stats for the day are printed

**Comment by MorganOnCode** [comment]
Hey @kinabalu - I would love to use this plugin again, in fact I've been trying to make my own. 
I'm getting a 410 error status in Obsidian console. 
Is this because the Oura API was updated to V2?

**Comment by kinabalu** [comment]
@MorganOnCode happy to review any PRs sent and test this out -- I don't have any hardware to test with right now so has been unfortunately difficult to test. And yes, 410 is probably because the API has moved to a different URL (v2 probably somewhere in there), so the calls to oura need to change

**Comment by objectmethod** [comment]
https://github.com/kinabalu/obsidian-oura-plugin/pull/10

**Comment by marcofeltmann** [comment]
Dear @objectmethod, thank you for the PR #10 

Unfortunately it does not work on my machine in Obsidian 1.5.12 via BRAT:

```
app.js:1 Uncaught (in promise) Error: Request failed, status 404
    at new t (app.js:1:1977769)
    at qG (app.js:1:1977961)
    at app.js:1:1978638
    at app.js:1:237056
    at Object.next (app.js:1:237161)
    at a (app.js:1:235879)
```

It does the same with a wrong API key like `no` and after I created a new API key.
Unfortunately I have no clue where to look for the used URI to dive into that one deeper.

**Comment by marcofeltmann** [comment]
Looks like `curl`ing the daily activity endpoint by hand works.

```
curl --location --request GET 'https://api.ouraring.com/v2/usercollection/daily_activity' \
--header 'Authorization: Bearer <token>'
```

Maybe the BRAT thingy did just not work? It shows v0.0.3 still.

**Comment by marcofeltmann** [comment]
Built it on my own and it has some interesting information in there.

```markdown
- Bedtime_Start:: 22:33:24
- Bedtime_End:: 22:33:24
- Sleep_Score:: 71
- Sleep_Efficiency:: undefined
- Sleep_Duration:: 00:00:00
- Total_Sleep:: 00:00:00
- Total_Awake:: 00:00:00
- Sleep_Latency:: 00:00:00
- Light_Sleep:: 00:00:00
- Rem_Sleep:: 00:00:00
- Deep_Sleep:: 00:00:00
- Day_Start:: 22:33:24
- Day_End:: 22:33:24
- Activity_Score:: null
- Low_Activity:: 00:00:00
- Medium_Activity:: 00:00:00
- High_Activity:: 00:00:00
- Rest_Activity:: 00:00:00
- Steps:: 5389
- Readiness_Score:: 66
```

Not sure if Mapping is broken. :thinking:

**Comment by andrewlombardictr** [comment]
sorry folks after the PR I didn't push a new tag version, 0.0.4 is now available so likely will be pulled from BRAT. Let me know if it's not working

**Comment by objectmethod** [comment]
Thanks, @andrewlombardictr.

Did it work for you now, @marcofeltmann?

**Comment by kinabalu** [comment]
closing as no word back from OP
